import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./styles.css";

const font = JetBrains_Mono ({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body className={`${font.className} bg-ash_background-500 max-w-screen-lg mx-auto`}>
                {children}
            </body>
        </html>
    );
}
